### PR TITLE
Fix subcommand defaultValue bug

### PR DESCRIPTION
**Pull request by itohatweb**
When a command that is build on subcommands (eg. !math) and you do not specify a sub command (eg. !math 1 3) the bot would error out.
Is there a better way of fixing that problem?

### CODE REVIEW

**Comment by Skillz4Killz** [comment]
@itohatweb You can specify a default subcommand.

**Comment by itohatweb** [comment]
I already tested that it did not work on my end. Following error would occur:
grafik

**Comment by itohatweb** [comment]
I have now tested it on multiple different servers and I always got the same error when I was not using the code of this PR.

**Comment by ayntee** [comment]
Can you provide reproducible code?

**Comment by itohatweb** [comment]
Example files:
math.ts: https://hasteb.in/jugurafu.js
test.ts: https://hasteb.in/azevaror.js

- !math add 1 2 (works)
- !math 1 2 (errors out)
- !testing (errors out)

Using the addition of this PR  the above 2 commands do not error out.

**Pull request merged**
